// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT0i0np6wO8zBOv9rJX-rdXbFhEostlqw',
    appId: '1:37499932366:web:d7add5ee508bf7166bca9f',
    messagingSenderId: '37499932366',
    projectId: 'banglado-f35a8',
    authDomain: 'banglado-f35a8.firebaseapp.com',
    storageBucket: 'banglado-f35a8.appspot.com',
    measurementId: 'G-ZL522PNND9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQxcdnUxgVRXEJM6lj8MTPPmhv0JHhg80',
    appId: '1:37499932366:android:1c264df95e4ec5646bca9f',
    messagingSenderId: '37499932366',
    projectId: 'banglado-f35a8',
    storageBucket: 'banglado-f35a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7JpZirUB2TywTmbtizuOCmtk62KxoDJQ',
    appId: '1:37499932366:ios:2987cc898133d5a16bca9f',
    messagingSenderId: '37499932366',
    projectId: 'banglado-f35a8',
    storageBucket: 'banglado-f35a8.appspot.com',
    iosBundleId: 'com.example.copy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7JpZirUB2TywTmbtizuOCmtk62KxoDJQ',
    appId: '1:37499932366:ios:90c548b101d8a7ea6bca9f',
    messagingSenderId: '37499932366',
    projectId: 'banglado-f35a8',
    storageBucket: 'banglado-f35a8.appspot.com',
    iosBundleId: 'com.example.copy.RunnerTests',
  );
}
