// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7I_t8Vf731WZebo85SMiH1KkXSOIpqFE',
    appId: '1:781683171753:web:678b461954bb06b6eba4b8',
    messagingSenderId: '781683171753',
    projectId: 'banglado-cabff',
    authDomain: 'banglado-cabff.firebaseapp.com',
    storageBucket: 'banglado-cabff.appspot.com',
    measurementId: 'G-ZNZ67ZQQ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaEQNYSIusEi8mjneCYo9ATtYr7ELHwJE',
    appId: '1:781683171753:android:56bd878c08b22ae0eba4b8',
    messagingSenderId: '781683171753',
    projectId: 'banglado-cabff',
    storageBucket: 'banglado-cabff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9cc9vjBcHbZIu4MgHkYXvdWXKCdnxuKc',
    appId: '1:781683171753:ios:aacbfda99e3c1e69eba4b8',
    messagingSenderId: '781683171753',
    projectId: 'banglado-cabff',
    storageBucket: 'banglado-cabff.appspot.com',
    iosBundleId: 'com.example.copy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9cc9vjBcHbZIu4MgHkYXvdWXKCdnxuKc',
    appId: '1:781683171753:ios:c3f69f723e536710eba4b8',
    messagingSenderId: '781683171753',
    projectId: 'banglado-cabff',
    storageBucket: 'banglado-cabff.appspot.com',
    iosBundleId: 'com.example.copy.RunnerTests',
  );
}
